name: ncf-env
channels:
  - default
dependencies:
  - python=3.12
  - pip<=25.2
  - pip:
    - pandas==2.2.3
    - numpy==2.3.0
    - mlflow==3.6.0
    - scikit-learn==1.5.2
    - tensorflow==2.20.0
    - scikeras==0.13.0